import { ImageResponse } from "next/og";

export const runtime = "edge";
export const alt = "메디컬 헤드스파 | medicalheadspa.kr";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

/**
 * Fallback dynamic OG image generated by Next.js.
 *
 * If a static `public/og-image.png` is present and referenced from
 * `metadata.openGraph.images`, that file takes precedence. This file
 * guarantees the site always has a branded OG image even if the static
 * asset is missing.
 */
export default function Image() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          background:
            "linear-gradient(135deg, #f7f5f0 0%, #eae4d6 50%, #f0ece1 100%)",
          fontFamily: "sans-serif",
          position: "relative",
        }}
      >
        {/* Brand navy border frame */}
        <div
          style={{
            position: "absolute",
            inset: 40,
            border: "2px solid rgba(15, 32, 39, 0.08)",
            borderRadius: 24,
          }}
        />

        {/* MH + medical cross logomark */}
        <div
          style={{
            display: "flex",
            alignItems: "flex-start",
            gap: 0,
            color: "#0f3a2f",
          }}
        >
          <div
            style={{
              fontSize: 280,
              fontWeight: 900,
              letterSpacing: -8,
              lineHeight: 1,
            }}
          >
            M
          </div>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              alignItems: "flex-start",
              marginLeft: -24,
              marginTop: 20,
            }}
          >
            <div
              style={{
                fontSize: 72,
                color: "#c4a77d",
                fontWeight: 900,
                lineHeight: 1,
                marginBottom: 8,
              }}
            >
              +
            </div>
            <div
              style={{
                fontSize: 280,
                fontWeight: 900,
                letterSpacing: -8,
                lineHeight: 1,
              }}
            >
              H
            </div>
          </div>
        </div>

        {/* Divider + URL */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 24,
            marginTop: 32,
          }}
        >
          <div
            style={{ width: 80, height: 2, background: "#c4a77d" }}
          />
          <div
            style={{
              fontSize: 42,
              color: "#0f3a2f",
              fontWeight: 600,
              letterSpacing: 0.5,
            }}
          >
            medicalheadspa.kr
          </div>
          <div
            style={{ width: 80, height: 2, background: "#c4a77d" }}
          />
        </div>

        {/* Tagline */}
        <div
          style={{
            marginTop: 24,
            fontSize: 26,
            color: "#0f3a2f",
            opacity: 0.7,
            fontWeight: 500,
          }}
        >
          전국 메디컬 헤드스파 · 두피 스캘프 케어 예약
        </div>
      </div>
    ),
    { ...size }
  );
}
